// تحميل المتغيرات الأساسية
apply from: "variables.gradle"

buildscript {

    ext.kotlin_version = '2.1.0'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {

        // Android Gradle Plugin
        classpath 'com.android.tools.build:gradle:8.9.1'

        // Google Services
        classpath 'com.google.gms:google-services:4.4.2'

        // Kotlin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {

    afterEvaluate { project ->

        if (project.hasProperty('android')) {

            project.android {

                // لازم 36 بسبب AndroidX الجديدة
                compileSdkVersion 36

                defaultConfig {
                    targetSdkVersion 36
                }

                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_17
                    targetCompatibility JavaVersion.VERSION_17
                }

                if (project.plugins.hasPlugin('kotlin-android')) {

                    kotlinOptions {
                        jvmTarget = "17"
                    }
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}